version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
  #   environment:
  #     - "discovery.type=single-node"
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - elk-network

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:7.15.0
  #   volumes:
  #     - ./logstash-kafka.conf:/usr/share/logstash/pipeline
  #   ports:
  #     - "5000:5000"
  #   environment:
  #     - "xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200"
  #   depends_on:
  #     - elasticsearch
  #     - kafka
  #   networks:
  #     - elk-network

  logger:
    build: .
    depends_on:
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=logs
    command: python app.py

# networks:
#   # elk-network: