version: '3'
services:

  zookeeper:
    ports:
      - '50000:2181'
    image: zookeeper:3.5.9 
  kafka:
    ports:
      - '50001:9092'
      - '50002:9093'
    depends_on:
      - zookeeper
      - logstash
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENERS: 'INTERNAL://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INTERNAL://:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_CREATE_TOPICS: 'logs:1:1'
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal 
    image: 'wurstmeister/kafka:2.13-2.8.1'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
  kibana:
    depends_on:
      - elasticsearch
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    volumes:
      - kibana-data:/usr/share/kibana/data
    ports:
     - ${KIBANA_PORT}:5601
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
  logstash:
   depends_on:
     - elasticsearch
   image: docker.elastic.co/logstash/logstash:${STACK_VERSION}
   ports:
    - 5044:5044
   volumes:
     - logstash-data:/usr/share/logstash/data
     - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
   environment:
     - xpack.monitoring.enabled=false
     - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

  logger:
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
      - kafka
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=logs
    entrypoint: ./startapp.sh

volumes:
  elasticsearch-data:
    driver: local
  kibana-data:
     driver: local
  logstash-data:
    driver: local

 